### PR TITLE
py 2/3 compatible print

### PR DESCRIPTION
**Pull request by fchapoton**
use a print syntax that works, with the same result, in both python2 and python3

### CODE REVIEW

**Comment by fchapoton** [comment]
ping ? this is a very simple change.

**Comment by kiwifb** [comment]
Sorry somehow I didn't get that one, I'll have to check my subscription feeds.

**Comment by kiwifb** [comment]
Do you have anything else you want for a 0.8.5 release?

**Comment by fchapoton** [comment]
no, nothing else.

**Pull request merged**
