### PR TITLE
add .travis.yml

### PR DESCRIPTION
**Pull request by rusydi**
This adds .travis.yml to make sure every commit is successfully build. It requires a user-account in https://travis-ci.org for BRiAl.

### CODE REVIEW

**Comment by kiwifb** [comment]
Is it possible to add several versions of boost to be tested? If it was possible I would like to test minimum boost and latest boost. I guess if it depends on trusty's repo the latter may be hard to achieve.

**Comment by kiwifb** [comment]
Inspecting some more I would also prefer if we used a "released" tarball of `m4ri` specifically from https://github.com/malb/m4ri/releases on github rather than bitbucket. It will still need to run autoreconf.

**Comment by kiwifb** [comment]
Why are you adding `/usr/local/lib` to `LD_LIBRARY_PATH`? `/usr/local/lib` should have priority over `/usr/libXX` already. Is it a feature of "trusty"?

**Comment by rusydi** [comment]
Hi

1. I have added minimum boost version required by BRiAl (1.58.0) and the latest boost version (1.65.1) to test the build.
2. The downloaded m4ri is now using the latest released tarbal from github.
3. Adding /usr/local/lib is apparently still needed to link the test cases with boost unit test library.
4. Note that executing "make check" requires linking the unit test with m4ri. I added "-lm4ri" in tests/Makefile.am. Is there a better solution for this ?

**Comment by rusydi** [comment]
The build results are available in https://travis-ci.org/rusydi/BRiAl

**Comment by kiwifb** [comment]
OK the `/usr/local/lib` stuff is weird but I have a feeling that's because trusty does something weird with libtool, that may be a debian behavior. Same with the `-lm4ri` that shouldn't be necessary but I'll dig that further, there may be something simple to do. 

In any case that run has already revealed a problem that will need addressing, so your work here is *very* valuable.

**Comment by kiwifb** [comment]
The problem with `-lm4ri` has to be a bug in the libtool used by trusty. We have 
```
libbrial_groebner_la_LIBADD = \
        $(top_builddir)/libbrial.la \
        $(LIBPNG_LIBADD) \
        $(M4RI_LIBS) \
        $(GD_LIBS)
```
so anything using `libbrial_groebner.la` like `Makefile.am` in the tests subfolder should get `-lm4ri`. And in fact it should also get the definitions for libpng and gd.

I see a lot of conversation related to this from 2012, still my gentoo system works. I will add something for systems that I see as broken in this regards.

**Comment by kiwifb** [comment]
It looks like the problem with boost is not limited to 1.65, I get it with 1.62 too. It is an incompatibility with gcc-6+. I'd say that's not a problem at the brial level but at the boost level.

**Comment by kiwifb** [comment]
Test suite pass with gcc-6 when you use `-std=gnu++98` which is annoying because I was planning to forbid that.

**Comment by kiwifb** [comment]
OK if you rebase on master you shouldn't need to add `-lm4ri` anywhere anymore.

**Comment by kiwifb** [comment]
OK done. Now next problem: boost and gcc 6 not liking each other in the test suite.

**Comment by rusydi** [comment]
Examining the log from https://travis-ci.org/rusydi/BRiAl/jobs/287865837, the problem is not between boost and gcc-6. The problem occur in compiling tests/BoolePolynomialTest.cc. My guess is that the way current test is written is not compatible with later version of Boost.Test

**Comment by kiwifb** [comment]
I haven't got the first clue on how to fix it.

**Comment by rusydi** [comment]
Note that g++-6 enable -std=c++14 by default. And in https://travis-ci.org/rusydi/BRiAl/jobs/287874607 i dont see we compile BRiAl with -std=c++11. We should add AX_CXX_COMPILE_STDCXX_11([noext],[mandatory]) in configure.ac.

**Comment by kiwifb** [comment]
I am planning to do something like that but I have just tried to build with "g++ -std=c++11" and I get the same failure (with gcc 6.4.0).

**Pull request merged**
