### PR TITLE
python3 print syntax

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by fchapoton** [comment]
Ping ?

**Comment by fchapoton** [comment]
**PING ?**

**Comment by kiwifb** [comment]
That's silly, how come I wasn't notified of those - wrong notification setting, that's why. Anyway that file is not currently installed by brial. I can still merge the request in case we get it back.

**Comment by kiwifb** [comment]
I am somewhat puzzled that github still says this can be merged when the file concerned is not in the repo anymore. Closing since it is gone for now.

**Pull request closed without merging**
