### PR TITLE
Use M4RI provided CFLAGS when building groebner. This should include …

### PR DESCRIPTION
**Pull request by kiwifb**
…any switches for the compiler.

### CODE REVIEW

**Comment by kiwifb** [comment]
As an example on my test machine m4ri.pc is

```
SAGE_ROOT=/home/frb15/sagemath/sage-brial
prefix=${SAGE_ROOT}/local
exec_prefix=${prefix}
libdir=${SAGE_ROOT}/local/lib
includedir=${prefix}/include

Name: M4RI
Description: Dense linear algebra over GF(2).
Version: 20140914
Libs: -L${libdir} -lm4ri -lm
Cflags: -I${includedir}/m4ri  -I${SAGE_ROOT}/local/include -g -fPIC -Wall -pedantic -O2  -mmmx -msse -msse2 -msse3 
```

so `M4RI_CFLAGS` will include all the switches from the `Cflags` line. Hopefully that is enough and I didn't clobber anything.

**Comment by kiwifb** [comment]
And if `m4ri` was getting its act together the `Libs` line should include flags for `libpng` if it was compiled with it, or an extra depend line.

**Comment by ohanar** [comment]
`M4RI_CFLAGS` pulls in flags that we might not want to include, e.g. `-O2`, `-g`, and `-fPIC`. In `<m4ri/m4ri_config.h>` contains a separate define for the flags that we actually want.

**Comment by kiwifb** [comment]
I reckon that `m4ri` `.pc` file stinks and indeed shouldn't have some of that stuff. OK, I'll see if I can come up with an alternative.

**Comment by kiwifb** [comment]
I have a vile hack that I will submit in another branch. But future work will be to fix `m4ri` configuration and `.pc` file then come back here and use this branch strategy.

**Pull request closed without merging**
