### PR TITLE
more detailed config.h.in with VERSION, etc

### LINKED ISSUE #46: VERSION in polybori/config.h ?
In Debian (brial 1.2.4) and Fedora (1.2.5) there is a handy macro VERSION, e.g.
```
/* Version number of package */
#define VERSION "1.2.5"
```
But not e.g. in Gentoo. Does it need another way to generate `polybori/config.h` ?

### PR DESCRIPTION
**Pull request by dimpase**
This will fix  #46

### CODE REVIEW

**Comment by kiwifb** [comment]
Did you just get that from autoheaders or did you get a bit more selective?

**Comment by dimpase** [comment]
just from autoheader. Then, if you look at the diff, you see it only adds stuff, doesn't remove anything.

**Comment by kiwifb** [comment]
If it is just autohedears you may as well remove the file and leave it be autogenerated like before. And then @SnarkBojuum will complain again. If you are just after the version, just add that.

**Comment by dimpase** [comment]
But what was his point to begin with? I don't get it.

**Comment by dimpase** [comment]
I imagine that `VERSION` can certainly crash with a hell of a lot of things. But, by right, `config,h` is an interal header, is should not be blindly included everwhere.

**Comment by kiwifb** [comment]
It is a pity, the original reporter didn't give more details and now doesn't seem to be able to answer calls. I am for a minimal fix unless proven it was all bogus.
The next thing is what time frame are we targetting. I am just feeling uneasy about doing a 1.2.9 release just for this.

**Comment by kiwifb** [comment]
Closing this as it cannot apply anymore.

**Pull request closed without merging**
