### PR TITLE
Fix unitialized iterators

### PR DESCRIPTION
**Pull request by saraedum**
I did not really know where to put the initializer of the empty vector so I put
it in its own file. I hope that's alright.

### CODE REVIEW

**Comment by kiwifb** [comment]
Anymore stuff or you think it is ready to go?

**Comment by saraedum** [comment]
I think that this is ready to go in.

**Comment by kiwifb** [comment]
There will be a new release tomorrow. I am doing that from my office machine.

**Comment by saraedum** [comment]
Great!

**Pull request merged**
