### PR TITLE
Expand testing to OSX with clang

### PR DESCRIPTION
**Pull request by kiwifb**

### CODE REVIEW

**Comment by saraedum** [comment]
I don't know much about travis but from my experience with other CI systems, it looks quite reasonable. You could probably make your life a bit easier by extracting boost with `-C boost --strip-components=1` so you do not have to have all those boost variables around but only one that lets you construct the URL.

**Comment by kiwifb** [comment]
OK still failed but some progress has been made. The number of failures is way down.

**Comment by kiwifb** [comment]
OK, after some testing, the issue with BoolePolynomialTest.cc is specific to OS X (at least with clang) but the last remaining tests are clang specific issue - I can reproduce them on linux with clang-5.0.1.

I am thinking of just removing some of those tests since I don't even know what they test.

**Comment by saraedum** [comment]
@kiwifb I would like to try to debug what's the problem here.  I can not reproduce it locally on my (linux) system with clang:
```
❯ clang --version                                                                                                                       master ◼
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by saraedum** [comment]
Hm, why are we setting `CXX` and `CC` like that here?
```
Setting environment variables from .travis.yml
$ export COMPILER=clang++
$ export BOOST_MAJOR_VERSION=1
$ export BOOST_MINOR_VERSION=65
$ export BOOST_MAINTENANCE_VERSION=1
$ export CXX=g++
$ export CC=gcc
```

**Comment by kiwifb** [comment]
Hum... Then may be it is not so much clang as libcxx from clang. Does your clang++ use libstdc++ from g++?

For your second post, I don't set either CC or CXX that way in `.travis.yml`. Eventually CXX will be set by `CXX=$COMPILER`, the C compiler is not so important as runtime is compatible.

**Comment by saraedum** [comment]
Ok. I don't think that I link against clang's libstdc++:
```
❯ ldd tests/.libs/unittests                                                                                                             master ◼
	linux-vdso.so.1 (0x00007ffdb8a0c000)
	libboost_unit_test_framework.so.1.66.0 => /usr/lib/libboost_unit_test_framework.so.1.66.0 (0x00007f7b98e58000)
	libbrial_groebner.so.3 => /usr/lib/libbrial_groebner.so.3 (0x00007f7b98935000)
	libbrial.so.3 => /usr/lib/libbrial.so.3 (0x00007f7b9869a000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f7b98464000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f7b9824d000)
	libm4ri-0.0.20140914.so => /usr/lib/libm4ri-0.0.20140914.so (0x00007f7b9801c000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f7b97cd0000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f7b97949000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f7b97732000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f7b9737b000)
	libboost_timer.so.1.66.0 => /usr/lib/libboost_timer.so.1.66.0 (0x00007f7b97175000)
	libboost_system.so.1.66.0 => /usr/lib/libboost_system.so.1.66.0 (0x00007f7b96f70000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f7b96d68000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f7b96b4a000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f7b995d2000)
	libboost_chrono.so.1.66.0 => /usr/lib/libboost_chrono.so.1.66.0 (0x00007f7b96941000)
```

**Comment by kiwifb** [comment]
Indeed you don't. So the last problem is not in clang but in libcxx. I can do something to exclude that. But that leave me with problem that I have no idea what those bits are testing.

**Comment by kiwifb** [comment]
OK travis now fails because sometimes the connection to sourceforge to download boost fails but stuff now passes on OS X. So I will merge and release 1.2.2 soon.

**Pull request merged**
